apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: django-app
  labels:
    app: django-svc
spec:
  type: NodePort
  ports:
    - port: 8000 # 클러스터 내부에서 Service가 사용하는 포트.
      targetPort: 8000 # Pod 내부에서 컨테이너가 사용하는 포트.
  selector:
    app: django-application