FROM python:3.11.4-slim-bullseye

# python envs
ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

RUN apt-get update && apt-get install -y

COPY ./requirements.txt /
RUN pip install -r ./requirements.txt

COPY ./backend/ /app/

# 컨테이너 빌드 시 사용할 포트 공개
EXPOSE 8000 8001

WORKDIR /app

# docker build -f Dockerfile.django -t django_app:1.0.0 .