FROM nginx:1.24.0-bullseye

# 컨테이너 내에서 Nginx 구성 파일을 복사
COPY ./nginx.conf /etc/nginx/nginx.conf

# 컨테이너 빌드 시 사용할 포트 공개
EXPOSE 80

# 컨테이너 실행 시 Nginx 서비스 시작
CMD ["nginx", "-g", "daemon off;"]

# docker build -f Dockerfile.nginx -t nginx_app:1.0.0 .