apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: django-app
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    events {
      worker_connections  1024;
    }

    http {

      # nginx 버전 안 나오게
      server_tokens off;

      include /etc/nginx/mime.types;
      
      client_header_timeout 1m;
      client_body_timeout 1m;
      client_max_body_size 50M;

      sendfile on;

      upstream backend {
        server django-service:8000;
      }

      server {
        listen 80;

        location / {
          index  index.html index.htm;
          try_files $uri $uri/ /index.html; 
        }

        location ~ ^/(admin|api) {
          proxy_pass http://backend;
          
          proxy_connect_timeout 1m;
          proxy_send_timeout 1m;
          proxy_read_timeout 1m;
          send_timeout 1m;

          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        # backend static
        location ~ ^/(static|media|)/(.*)$ {
          add_header Access-Control-Allow-Origin *;

          alias /app/$1/$2;
        }
        
      }
    }