apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: django-app
  labels:
    app: postgresql-svc
spec:
  type: NodePort # default는 ClusterIP
  ports:
    - port: 5432 # 클러스터 내부에서 Service가 사용하는 포트.
      targetPort: 5432 # Pod 내부에서 컨테이너가 사용하는 포트.
      nodePort: 30004 # 클러스터 외부에서 접근하기 위한 노드의 포트, 범위 30000-32767
  selector:
    app: postgresql